import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="min-h-screen bg-[#dfecfaff]">
      <div className="container mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="max-w-9xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold bg-clip-text text-gray-900 mb-4">
              Privacy Policy
            </h1>
            <div className="w-24 h-1 bg-slate-900 mx-auto rounded-full"></div>
          </div>
         
          
          {/* Content Card */}
          <div className="bg-[#fbfdffff] rounded-2xl shadow-xl p-6 sm:p-8 lg:p-12">
            {/* Introduction */}
            <div className="mb-8">
              <p className="text-gray-700 text-lg leading-relaxed mb-4">
                This privacy policy describes our policies and procedures on the collection, use and disclosure of your information when you use the service. Your privacy rights and how the law protects You.
              </p>
              <p className="text-gray-700 text-lg leading-relaxed">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>
            </div>

            {/* Interpretation and Definitions */}
            <section className="mb-10">
              <h2 className="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-blue-200 pb-2">
                Interpretation and Definitions
              </h2>
              
              <div className="mb-6">
                <h3 className="text-2xl font-semibold text-gray-800 mb-3">Interpretation</h3>
                <p className="text-gray-700 leading-relaxed">
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
              </div>

              <div>
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Definitions</h3>
                <p className="text-gray-700 mb-4">For the purposes of this Privacy Policy:</p>
                
                <div className="grid gap-4">
                  {[
                    { term: "Account", definition: "means a unique account created for You to access our Service or parts of our Service." },
                    { term: "Affiliate", definition: "means an entity that controls, is controlled by or is under common control with a party, where 'control' means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority." },
                    { term: "Company", definition: "(referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to PIONEER GIRLS JUNIOR ACADEMY, P.O. Box 33-01015 Thika Rd, Nairobi" },
                    { term: "Cookies", definition: "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." },
                    { term: "Country", definition: "refers to: Kenya" },
                    { term: "Device", definition: "means any device that can access the Service such as a computer, a cellphone or a digital tablet." },
                    { term: "Personal Data", definition: "is any information that relates to an identified or identifiable individual." },
                    { term: "Service", definition: "refers to the Website." },
                    { term: "Service Provider", definition: "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." },
                    { term: "Usage Data", definition: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
                    { term: "Website", definition: "refers to PIONEER GIRLS JUNIOR ACADEMY, accessible from https://www.pioneergirlsjunioracademy.co.ke/" },
                    { term: "You", definition: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." }
                  ].map((item, index) => (
                    <div key={index} className="bg-gray-50 rounded-lg p-4 border-l-4 border-blue-500">
                      <p className="text-gray-700">
                        <span className="font-semibold text-gray-900">{item.term}:</span> {item.definition}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* Collecting and Using Your Personal Data */}
            <section className="mb-10">
              <h2 className="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-blue-200 pb-2">
                Collecting and Using Your Personal Data
              </h2>

              <div className="mb-6">
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Types of Data Collected</h3>
                
                <div className="mb-6">
                  <h4 className="text-xl font-semibold text-blue-600 mb-3">Personal Data</h4>
                  <p className="text-gray-700 mb-4 leading-relaxed">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                  </p>
                  <div className="bg-blue-50 rounded-lg p-4">
                    <ul className="list-disc list-inside text-gray-700 space-y-1">
                      <li>Email address</li>
                      <li>Usage Data</li>
                    </ul>
                  </div>
                </div>

                <div className="mb-6">
                  <h4 className="text-xl font-semibold text-blue-600 mb-3">Usage Data</h4>
                  <p className="text-gray-700 mb-4 leading-relaxed">
                    Usage Data is collected automatically when using the Service.
                  </p>
                  <p className="text-gray-700 mb-4 leading-relaxed">
                    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                  </p>
                  <p className="text-gray-700 mb-4 leading-relaxed">
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                  </p>
                  <p className="text-gray-700 leading-relaxed">
                    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                  </p>
                </div>
              </div>

              {/* Tracking Technologies and Cookies */}
              <div className="mb-8">
                <h3 className="text-2xl font-semibold text-gray-800 mb-4">Tracking Technologies and Cookies</h3>
                <p className="text-gray-700 mb-4 leading-relaxed">
                  We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                </p>
                
                <div className="bg-amber-50 rounded-lg p-4 mb-4 border-l-4 border-amber-500">
                  <p className="text-gray-700">
                    <span className="font-semibold text-gray-900">Cookies or Browser Cookies:</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                  </p>
                </div>

                <p className="text-gray-700 mb-4 leading-relaxed">
                  Cookies can be 'Persistent' or 'Session' Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                </p>

                <p className="text-gray-700 mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>

                <div className="grid gap-4 sm:grid-cols-1 lg:grid-cols-1">
                  {[
                    {
                      title: "Necessary / Essential Cookies",
                      type: "Session Cookies",
                      admin: "Us",
                      purpose: "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."
                    },
                    {
                      title: "Cookies Policy / Notice Acceptance Cookies",
                      type: "Persistent Cookies",
                      admin: "Us",
                      purpose: "These Cookies identify if users have accepted the use of cookies on the Website."
                    },
                    {
                      title: "Functionality Cookies",
                      type: "Persistent Cookies",
                      admin: "Us",
                      purpose: "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."
                    }
                  ].map((cookie, index) => (
                    <div key={index} className="bg-green-50 rounded-lg p-4 border border-green-200">
                      <h5 className="font-semibold text-green-800 mb-2">{cookie.title}</h5>
                      <div className="text-sm text-gray-600 mb-2">
                        <p><strong>Type:</strong> {cookie.type}</p>
                        <p><strong>Administered by:</strong> {cookie.admin}</p>
                      </div>
                      <p className="text-gray-700 text-sm leading-relaxed">
                        <strong>Purpose:</strong> {cookie.purpose}
                      </p>
                    </div>
                  ))}
                </div>

                <p className="text-gray-700 mt-4 leading-relaxed">
                  For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
                </p>
              </div>
            </section>

            {/* Use of Your Personal Data */}
            <section className="mb-10">
              <h2 className="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-blue-200 pb-2">
                Use of Your Personal Data
              </h2>
              <p className="text-gray-700 mb-4">The Company may use Personal Data for the following purposes:</p>
              
              <div className="grid gap-3">
                {[
                  { title: "To provide and maintain our Service", desc: "including to monitor the usage of our Service." },
                  { title: "To manage Your Account", desc: "to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user." },
                  { title: "For the performance of a contract", desc: "the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service." },
                  { title: "To contact You", desc: "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation." },
                  { title: "To provide You", desc: "with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information." },
                  { title: "To manage Your requests", desc: "To attend and manage Your requests to Us." },
                  { title: "For business transfers", desc: "We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred." },
                  { title: "For other purposes", desc: "We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience." }
                ].map((item, index) => (
                  <div key={index} className="bg-purple-50 rounded-lg p-4 border-l-4 border-purple-500">
                    <p className="text-gray-700">
                      <span className="font-semibold text-purple-800">{item.title}:</span> {item.desc}
                    </p>
                  </div>
                ))}
              </div>

              <div className="mt-6">
                <p className="text-gray-700 mb-4 font-medium">We may share Your personal information in the following situations:</p>
                <div className="grid gap-3">
                  {[
                    { title: "With Service Providers", desc: "We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You." },
                    { title: "For business transfers", desc: "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company." },
                    { title: "With Affiliates", desc: "We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us." },
                    { title: "With business partners", desc: "We may share Your information with Our business partners to offer You certain products, services or promotions." },
                    { title: "With other users", desc: "when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside." },
                    { title: "With Your consent", desc: "We may disclose Your personal information for any other purpose with Your consent." }
                  ].map((item, index) => (
                    <div key={index} className="bg-orange-50 rounded-lg p-4 border-l-4 border-orange-500">
                      <p className="text-gray-700">
                        <span className="font-semibold text-orange-800">{item.title}:</span> {item.desc}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* Additional Sections */}
            {[
              {
                title: "Retention of Your Personal Data",
                content: [
                  "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.",
                  "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods."
                ]
              },
              {
                title: "Transfer of Your Personal Data",
                content: [
                  "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
                  "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
                  "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information."
                ]
              },
              {
                title: "Delete Your Personal Data",
                content: [
                  "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.",
                  "Our Service may give You the ability to delete certain information about You from within the Service.",
                  "You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.",
                  "Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so."
                ]
              },
              {
                title: "Security of Your Personal Data",
                content: [
                  "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security."
                ]
              },
              {
                title: "Children's Privacy",
                content: [
                  "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
                  "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information."
                ]
              },
              {
                title: "Links to Other Websites",
                content: [
                  "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
                  "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services."
                ]
              },
              {
                title: "Changes to this Privacy Policy",
                content: [
                  "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
                  "We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the 'Last updated' date at the top of this Privacy Policy.",
                  "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page."
                ]
              }
            ].map((section, index) => (
              <section key={index} className="mb-10">
                <h2 className="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-blue-200 pb-2">
                  {section.title}
                </h2>
                {section.content.map((paragraph, pIndex) => (
                  <p key={pIndex} className="text-gray-700 leading-relaxed mb-4">
                    {paragraph}
                  </p>
                ))}
              </section>
            ))}

            {/* Disclosure Section */}
            <section className="mb-10">
              <h2 className="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-blue-200 pb-2">
                Disclosure of Your Personal Data
              </h2>
              
              <div className="mb-6">
                <h3 className="text-2xl font-semibold text-gray-800 mb-3">Business Transactions</h3>
                <p className="text-gray-700 leading-relaxed">
                  If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                </p>
              </div>

              <div className="mb-6">
                <h3 className="text-2xl font-semibold text-gray-800 mb-3">Law enforcement</h3>
                <p className="text-gray-700 leading-relaxed">
                  Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                </p>
              </div>

              <div>
                <h3 className="text-2xl font-semibold text-gray-800 mb-3">Other legal requirements</h3>
                <p className="text-gray-700 mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                <div className="bg-red-50 rounded-lg p-4">
                  <ul className="list-disc list-inside text-gray-700 space-y-2">
                    <li>Comply with a legal obligation</li>
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>Protect the personal safety of Users of the Service or the public</li>
                    <li>Protect against legal liability</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Contact Section */}
            <section className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl p-6 sm:p-8">
              <h2 className="text-3xl font-bold text-gray-800 mb-6 text-center">Contact Us</h2>
              <div className="text-center">
                <p className="text-gray-700 mb-4 text-lg">
                  If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <div className="inline-flex items-center justify-center bg-white rounded-lg px-6 py-3 shadow-md">
                  <span className="text-blue-600 font-medium">By email: </span>
                  <a 
                    href="mailto:groupit@pioneergroupofschools.co.ke" 
                    className="text-blue-600 font-semibold ml-2 hover:text-blue-800 transition-colors duration-200"
                  >
                    groupit@pioneergroupofschools.co.ke
                  </a>
                </div>
              </div>
            </section>
            {/* Footer */}
            <div className="text-center mt-16">
              <div className="inline-flex items-center space-x-2 text-gray-500">
                <div className="w-2 h-2 bg-yellow-500 rounded-full animate-pulse"></div>
              <span className="text-sm font-medium">
                  Last updated: {new Date().toLocaleDateString(undefined, {
                    day: 'numeric',
                    month: 'long',
                    year: 'numeric',
                  })}
                </span>
                <div className="w-2 h-2 bg-orange-500 rounded-full animate-pulse"></div>
              </div>
            </div>
                
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;